image: hashicorp/terraform:latest


stages:
  - build
  - plan
  - deploy

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  TF_VAR_bucket_name: $BUCKET_NAME
  TF_VAR_environment: $ENVIRONMENT
  TF_VAR_function_name: $FUNCTION_NAME
  TF_VAR_api_name: $API_NAME
  TF_VAR_region: $REGION
  TF_VAR_resize-prefix: $RESIZE_PREFIX
  TF_VAR_profile: $PROFILE
  TF_VAR_cdn_url: $CDN_URL
  TF_VAR_source_bucket: $SOURCE_BUCKET


.install-dependencies:
  before_script:
  stage: [build]
  script: |
    #!/usr/bin/env bash
    set -e
    echo "Installing dependencies"
    # installing sam cli and aws cli
    pip install awscli --upgrade --user
    pip install aws-sam-cli --upgrade --user



build:
  stage: build
  script: |
    #!/bin/bash
    set -e
    
    cd lambda-resizer
    sam build
  
  only:
    - main
  artifacts:
    paths:
      - lambda-resizer/.aws-sam/build


plan:
  stage: plan
  script:
    - terraform init
    - terraform plan 
  only:
    - main

deploy:
  stage: deploy
  script:
    - terraform init
    - terraform plan
    - terraform apply -auto-approve
  only:
    - main
  environment:
    name: production
  when: manual
